version: "3"

services:
  nginx-projects:
    image: nginx:alpine
    expose:
      - 80
      - 5000
    container_name: nginx-projects
    volumes:
      - ./nginx-projects.conf:/etc/nginx/conf.d/nginx-projects.conf:ro
    environment:
      - VIRTUAL_HOST=projects.impiyush.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=projects.impiyush.com
      - LETSENCRYPT_EMAIL=piyush@impiyush.com
    restart: unless-stopped

  usbills:
    build:
        context: ./Recognize_US_Bills
        dockerfile: Dockerfile
    container_name: usbills
    ports:
        - 5000:5000
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy


      
